### ISSUE TITLE
Refined complexity analysis

### ISSUE THREAD

**Issue by FlippieCoetser** [kisstkondoros/gulp-tsmetrics#1]
As a **QA Engineer**,
When I **review** the **output** from **gulp-tsmetrics**,
I want to **only see** the complexity of each **method** in a **Class**.

Note:
- The complexity of properties in a Class should be 0 and can be omitted from the output. 
- The same would apply for non-method blocks of code in a file. Example: Interfaces, Import declarations
- By using the description field, a filter can be applied before the output is produced so that the output only produces a report of complexity for each method in a class.
- Caution, the complexity of a complete Class is not the sum of the complexity of each method in the Class.
- Calculating the complexity will require a lot of effort, as it will require the count of the pathways between the different methods. See: https://coderanch.com/t/98702/patterns/Calculating-Cyclomatic-complex-class. Recommend to tackle the complexity of a Class as a different feature request in a next release. If you are interested I can get another developer or two to help...

**Comment by kisstkondoros** [comment]
Hi,

First of all thanks for the detailed request!

Please have a look at https://github.com/kisstkondoros/gulp-tsmetrics/blob/master/test.ts#L78. I hope with the new version and the new filters you can achieve the expected result 😄 

About the class level complexity: it's definitely a bigger topic which I don't have time to bother with at the moment sorry. PR's are welcome. 😃

**Comment by kisstkondoros** [comment]
I'm closing this now, but feel free to reopen it!
